name: CI Secrets Example

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
      GOOGLE_API_KEY: ${{ secrets.GOOGLE_API_KEY }}
    steps:
      - uses: actions/checkout@v4

      - name: Validate secret injection
        run: |
          if [ -z "${OPENAI_API_KEY}" ] || [ -z "${GOOGLE_API_KEY}" ]; then
            echo "Secrets are missing. Define OPENAI_API_KEY and GOOGLE_API_KEY in repository secrets."
            exit 1
          fi

      - name: Show masked keys
        run: |
          echo "OpenAI key length: ${#OPENAI_API_KEY}"
          echo "Google key length: ${#GOOGLE_API_KEY}"
